language: php

php:
- 5.5

before_script:
   # Install Apache
   - sudo apt-get update
   - sudo apt-get install apache2 libapache2-mod-fastcgi
   # enable php-fpm
   - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
   - sudo a2enmod rewrite actions fastcgi alias
   - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
   - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
   # configure apache virtual hosts
   - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
   - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
   - sudo service apache2 restart
   - composer install --dev --prefer-dist

  # XVFB
   - "export DISPLAY=:99.0"
   - "Xvfb :99.0 -extension RANDR > /dev/null &"

  # Window manager
   - echo "c10"
   - "sudo apt-get install fluxbox -y --force-yes"
   - echo "c11"
   - "fluxbox &"

  # Selenium server
   - "wget http://selenium-release.storage.googleapis.com/2.52/selenium-server-standalone-2.52.0.jar"
   - "java -jar selenium-server-standalone-2.52.0.jar > /dev/null 2>/dev/null &"
   - sleep 30 # gives enough time to Selenium to start

script:
   - php .travis/traviswebserverckecker.php http://localhost/joomla-cms/installation/index.php # Test apache
   - mv tests/acceptance.suite.dist.yml tests/acceptance.suite.yml # Create travis system tests config file
   - "wget http://codeception.com/codecept.phar"
   - php ./codecept.phar build
   - php ./codecept.phar run acceptance

